version: '2'
services:
  freeradius-demo1:
    command: freeradius -X
    container_name: freeradius-demo1
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - "./certs:/certs"