version: '2'
services:
  freeradius-demo1:
    command: freeradius -X
    container_name: freeradius-demo4
    hostname: freeradius-demo
    env_file: .env
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - "./certs:/certs"
      - "./home-peap-eap-mschapv2.conf:/home-peap-eap-mschapv2.conf"
      - "./eduroam-peap-eap-mschapv2.conf:/eduroam-peap-eap-mschapv2.conf"